/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Name } from "./Name";
export * as factories from "./factories";
export { Name__factory } from "./factories/Name__factory";
