/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as abcSol from "./abc.sol";
export type { abcSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export type { Name } from "./abc.sol/Name";
export { Name__factory } from "./factories/abc.sol/Name__factory";
export { Lock__factory } from "./factories/Lock__factory";
